### ISSUE TITLE
Point 5

### ISSUE THREAD

**Issue by VimanyuAgg** [VimanyuAgg/Job-Portal-Project#5]
Job seekers can search for open job positions
Search by text the user types in, which can be a job title, a company name, a skill, a mix of them, or basically, any arbitrary piece of text. A word in the text can be matched against any part of a job posting.
Search by filters
Company name (allow multiple)
Location (city names, allow multiple)
Salary range (can be a single value, an open range, or a close range)
You can add more filters if you prefer. 
Within each filter type, the relationship between the multiple values is OR; e.g., if you specify both Cisco and IBM as the company filter, the it matches a job from Cisco or IBM . The different filters and free text work together with AND; i.e., all need to be matched. For example, If you specify both the company fitler and the location filter, a matching job must match both the two filters.
The layout of search result is up to you, but you need to support paging in case the number of matching jobs goes beyond one page, which contains up to 10 jobs.

**Comment by n3o-Bhushan** [comment]
Closing
