### ISSUE TITLE
Point 7

### ISSUE THREAD

**Issue by VimanyuAgg** [VimanyuAgg/Job-Portal-Project#6]
Apply for a position
A user can apply for a selected position in search result page or the interested jobs page.
A user can choose to apply with his profile, or attach a resume. In both cases, the user name and email from the user’s profile becomes part of the application.
For any apply operation, the user would receive an email notification with the information of position(s).
You need to provide a view for a user to browse or cancel his applications.
Each application has a status, Pending, Offered, Rejected, OfferAccepted, OfferRejcted, or Cancelled. The latter four states are also called terminal state. 
A user can cancel a pending application and reject an offered application.
The user can cancel (or reject) one or more applications (or offers) in one transaction.
The company can cancel any application that is not in a terminal state. 
Jobs of all states need to show up in the application view.
A user cannot have more than 5 pending applications. 
A user cannot apply for the same position again if the previous application is not in a terminal state.
For any status change of an application, the job seeker receives an email update as well.

**Comment by sidharthbhasin** [comment]
Completed.
