### ISSUE TITLE
Point 10,11

### ISSUE THREAD

**Issue by VimanyuAgg** [VimanyuAgg/Job-Portal-Project#7]
A company needs to provide basic information upon registration
Name
Website
Logo image URL
Address of headquarters
Description
		…
	Company can edit and update its own information at any time.

11. Company can post new positions into the system. A position contains at least the following information
Title
Description
Responsibilities
Office location
Salary
A company can edit and update its information mentioned above. When a job is updated, all the current applicants (applications in terminal states are not considered) are notified about the change.

**Comment by VimanyuAgg** [comment]
Need to handle update operation

**Comment by sidharthbhasin** [comment]
Everything working as requirement
